spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Ram@2005
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  custom:
    name: My name is Ram
    email: ram@gmail.com

